version: '3'
services:
  master-0:
    stop_signal: SIGINT
    container_name: master-0
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=0
    networks:
      - testing_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./persistance/master/events.log:/persistance/events.log
  
  master-1:
    stop_signal: SIGINT
    container_name: master-1
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=1
    networks:
      - testing_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./persistance/master/events.log:/persistance/events.log

  master-2:
    stop_signal: SIGINT
    container_name: master-2
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=2
    networks:
      - testing_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./persistance/master/events.log:/persistance/events.log

  # client-manager:
  #   stop_signal: SIGINT
  #   container_name: client-manager
  #   image: client-manager:latest
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   networks:
  #     - testing_net
  #   volumes:
  #     - ./persistance/client-manager:/persistance

  # filter-q1:
  #   stop_signal: SIGINT
  #   container_name: filter-q1
  #   image: filter-q1:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   networks:
  #     - testing_net
  #   volumes:
  #     - ./persistance/filter-q1:/persistance

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24