version: '3'
services:
  master-0:
    stop_signal: SIGINT
    container_name: master-0
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=0
    networks:
      - testing_net
  
  master-1:
    stop_signal: SIGINT
    container_name: master-1
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=1
    networks:
      - testing_net

  master-2:
    stop_signal: SIGINT
    container_name: master-2
    image: master:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MY_MASTER_ID=2
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24